
backend:
  name: github
  repo: paris-liam/ryanpedia

media_folder: assets
collections:
  - name: sections
    label: Sections
    folder: posts
    create: true
    fields:
      - { name: title, label: name}
      - { name: num, label: order}
      - { name: type, label: type, widget: hidden, default: 'section' }
      - { name: body, label: Post, widget: markdown }
